server:
  port: 8080

spring:
  data:
    mongodb:
      uri:  mongodb://root:root@localhost:27017/example?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bookings_project
    username: root
    password: root

app:
  kafka:
    topicToRead: user-statistics, booking-statistics
    topicToWrite: order-topic
    kafkaMessageGroupId: "kafka-message-group-id"


